import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/app/components/partials/Header";
import Footer from "./components/partials/Footer";

export const metadata: Metadata = {
  title: "The 18",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning className="scroll-smooth">
      <body
        className={cn(
          "text-lg text-dark selection:bg-dark selection:text-white"
        )}
      >
        <Header />
        <main className="lg:space-y-50 container space-y-20 scroll-smooth">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
